title: "[의사결정] YYYY-MM-DD - 결정 내용 요약"
labels: ["의사결정"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 의사결정 로그
        팀의 중요한 의사결정을 기록합니다. 회의, Slack, GitHub 등 모든 채널의 결정사항을 투명하게 문서화합니다.

  - type: input
    id: decision-date
    attributes:
      label: 📅 의사결정 일시
      description: 결정이 이루어진 날짜와 시간
      placeholder: "2025-10-23 14:30"
    validations:
      required: true

  - type: dropdown
    id: decision-category
    attributes:
      label: 🏷️ 의사결정 분류
      description: 의사결정 영역을 선택하세요
      options:
        - 기술/아키텍처
        - 제품/기획
        - 운영/프로세스
        - 인사/조직
        - 비즈니스/전략
    validations:
      required: true

  - type: dropdown
    id: decision-source
    attributes:
      label: 📍 결정 출처
      description: 의사결정이 이루어진 채널
      options:
        - 정기 회의
        - 긴급 회의
        - Slack 논의
        - GitHub Discussion
        - GitHub Issue/PR
        - 1:1 논의
    validations:
      required: true

  - type: textarea
    id: participants
    attributes:
      label: 👥 참여자
      description: 의사결정에 참여한 인원 (@멘션)
      placeholder: "@reus-jeon @garden92 @NO-Y-R"
    validations:
      required: true

  - type: textarea
    id: decision-context
    attributes:
      label: 🔍 의사결정 배경
      description: 왜 이 의사결정이 필요했는지 배경 설명
      placeholder: |
        - 문제: 현재 REST API 방식으로는 N+1 쿼리 문제 발생
        - 필요성: 성능 개선 및 클라이언트 유연성 향상
        - 고려사항: 학습 곡선, 기존 시스템과의 호환성
    validations:
      required: true

  - type: textarea
    id: decision-content
    attributes:
      label: ✅ 의사결정 내용
      description: 내린 결정의 구체적인 내용
      placeholder: |
        **결정:**
        - GraphQL을 새로운 API 표준으로 채택
        - Apollo Server 사용
        - 기존 REST API는 점진적 마이그레이션 (3개월 내)

        **근거:**
        - N+1 쿼리 문제 해결 가능
        - 클라이언트 요구사항에 유연하게 대응
        - TypeScript와의 시너지
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔀 검토된 대안
      description: 고려했던 다른 선택지와 기각 이유
      placeholder: |
        **대안 1: REST API 최적화**
        - 기각 이유: 근본적 해결 불가, 단기적 처방

        **대안 2: gRPC**
        - 기각 이유: 웹 클라이언트 지원 미흡, 학습 곡선 높음
    validations:
      required: false

  - type: dropdown
    id: impact-level
    attributes:
      label: 📊 영향 범위
      description: 이 결정이 미치는 영향의 크기
      options:
        - 🔴 높음 (전사/시스템 전체)
        - 🟡 중간 (특정 서비스/팀)
        - 🟢 낮음 (특정 기능/컴포넌트)
    validations:
      required: true

  - type: textarea
    id: affected-areas
    attributes:
      label: 🎯 영향 받는 영역
      description: 이 결정으로 영향받는 레포지토리, 서비스, 팀
      placeholder: |
        - 레포지토리: cm-office, cm-cointalk, core-supabase
        - 서비스: 전체 백엔드 API
        - 팀: Backend 팀, Frontend 팀
    validations:
      required: true

  - type: textarea
    id: action-items
    attributes:
      label: 📌 실행 계획
      description: 의사결정 실행을 위한 Action Items
      placeholder: |
        | 작업 | 담당자 | 기한 | 상태 |
        |------|--------|------|------|
        | GraphQL 스키마 설계 | @backend-lead | 10/30 | 진행중 |
        | Apollo Server 구축 | @engineer1 | 11/05 | 대기 |
        | 문서화 | @tech-writer | 11/10 | 대기 |
      value: |
        | 작업 | 담당자 | 기한 | 상태 |
        |------|--------|------|------|
        | | | | |
    validations:
      required: false

  - type: textarea
    id: related-links
    attributes:
      label: 🔗 관련 링크
      description: 관련 이슈, PR, 문서, Slack 스레드 등
      placeholder: |
        - 관련 이슈: #123
        - 참고 문서: https://...
        - Slack 논의: https://semicolon-team.slack.com/archives/...
    validations:
      required: false

  - type: input
    id: review-date
    attributes:
      label: 🔄 재검토 일정
      description: 이 결정을 재검토할 날짜 (선택사항)
      placeholder: "2026-01-23 (3개월 후)"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 📎 추가 메모
      description: 기타 참고사항이나 특이사항
      placeholder: "향후 고려사항, 리스크, 의견 등"
    validations:
      required: false
